name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Java (Нужно для Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build APK (Local)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        # Убираем --output, так как EAS кладет файл в папку по умолчанию, мы найдем его позже
        run: eas build --platform android --profile preview --local --non-interactive

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./*.apk
